	

	<?php 

	if (!empty($error)):
		//header('Refresh:10; url=index.php');
		?>
	<div class="alert alert-dismissible alert-warning text-center">
		  <a href="index.php" class="close" data-dismiss="alert">&times;</a>

  		<h4 class="alert-heading">Warning!</h4>
   		<?php foreach ($error as $key => $value): 	?>
  		<p class="mb-0"><?= $value ?></p>
   		<?php endforeach ?>
   		 <a href="index.php"class="btn btn-warning col-lg-2  col-md-4 col-sm-6 m-2" >RETOUR</a> 
	</div>

	<?php endif ?>
