


	<div class="container">
		<div class = "page-header p-5">
			<h2 class="text-center text-secondary">Veuillez compléter soignement ce formulaire  d'inscription </h2>
		</div>

		<form action="addUser.php" method="post" enctype="multipart/form-data">
			<fieldset class="scheduler-border ">
				<legend class="scheduler-border">Vos coordonnées:</legend>
				<div class="row ">
					<div class= " col-lg-4  col-md-6 col-sm-12 mt-3">
				<label  classs="control-label" for="nom">Votre nom:</label>
				<input  class="form-control" type="text" name="nom" id="nom">
				<div class = "text-danger" id="invalidnom"></div>
				<div class="valid-feedback" id="validnom"></div>
					</div>
					<div class=" col-lg-4  col-md-6 col-sm-12 mt-3">
				<label class="control-label" for="prenom">Votre prénom:</label>
				<input class="form-control" type="text" name="prenom" id="prenom">
				<div class = "text-danger" id="invalidprenom"></div>
				<div class="valid-feedback" id="validprenom"></div>
					</div>
					<div class=" col-lg-4 col-md-6 col-sm-12 mt-3">
				<label class="control-label" for="email">Votre email:</label>
				<input class="form-control" type="email" name="email" id="email">
				<div class="text-danger" id="invalidemail"></div>
				<div class="valid-feedback" id="validmail"></div>
					</div>
					<div class="col-lg-4  col-md-6 col-sm-12 mt-3">
				<label class="control-label" for="pays">Votre pays:</label>
				<select class="form-control" name="pays" id="pays">
					<option value="tunisie" selected="selected">TUNISIE</option>
					<option value="france">FRANCE</option>
				</select>
					</div>
					<div class=" col-lg-4  col-md-6 col-sm-12 mt-3">
						<label class="control-label" for="tel">Votre Tel:</label>
						<div class=" input-group">
							<div class="input-group-prepend">
       						 	<span class="input-group-text" id="préfixe">00216</span>
     					 	</div>
							<input class="form-control" type="text" name="tel" id="tel">
						</div>
						<div class="text-danger" id="invalidetel"></div>
						<div class="valid-feedback" id="validtel"></div>
					</div>
					<div class=" col-lg-4  col-md-6 col-sm-12 mt-3">
				<div class="form-group">
      				<label for="exampleInputFile">Votre photo:</label>
      				<input type="file" class="form-control-file"  name="fileToUpload" accept=".png,.jpg" id="fileToUpload">
      				<div class="text-danger" id="invalidefile"></div>
      				<div class="valid-feedback" id="validfile"></div>
   			 	</div>	
          			</div>
          		</div>       
			</fieldset>
			<fieldset class="scheduler-border">
				<legend class="scheduler-border"> Selectionner votre profil :</legend>
				<div class="row">
					<div class="form-check col-lg-4 mt-3">
						<label class="form-check-label" for="Etudiant">
  						<input class="form-check-input" type="radio" name="profil"  value="Etudiante" id="Etudiante">Etudiante</label>
  					</div>
  					<div class="breadcrumb col-lg-8 hidden" id="espaceEtudiant">
						<label class="control-label" for="université">Votre université:</label>
						<input class="form-control" type="text" name="university" id="université" >
						<div class="text-danger" id="invaliduniversité"></div>
						<div class="valid-feedback" id="validuniversité"></div>
					</div>
				</div>
				<div class="row">
  					<div class="form-check col-lg-4 mt-3">
  						<label  class="form-check-label" for="Professionnel">
  						<input class="form-check-input" type="radio" name="profil"  value="Professionnel" id="Professionnel">Professionnel:</label>
					</div>
					<div class="breadcrumb col-lg-8 hidden" id="espaceProf">
						<label class="control-label m-3" for="activité">Votre activité:</label>
  						<div class="form-check form-check-inline m-3" >
  							<input class="form-check-input" type="checkbox"  name="activity[]" id="Web" value="Web">
  							<label class="form-check-label" for="Web">Web</label>
						</div>
						<div class="form-check form-check-inline m-3">
  							<input class="form-check-input" type="checkbox"  name="activity[]"  id="Mobile" value="Mobile">
  							<label class="form-check-label" for="Mobile">Mobile</label>
						</div>
						<div class="form-check form-check-inline m-3">
  							<input class="form-check-input" type="checkbox"  name="activity[]" id="IOT" value="IOT">
  							<label class="form-check-label" for="IOT">IOT</label>
						</div>
						<div class="form-check form-check-inline m-3 ">
  							<input class="form-check-input" type="checkbox"  name="activity[]" id="Blockchain" value="Blockchain">
  							<label class="form-check-label" for="Blockchain">Blockchain</label>
						</div>
						<div class="text-danger" id="invalidactivity"></div>
						<div class="valid-feedback" id="validactivity"></div>
					</div>
					
				</div>
			</fieldset>
 	  		<div class="form-group  d-flex justify-content-center">
                 <button type="submit" class="btn btn-success col-lg-2 col-md-4 col-sm-6 m-2" id="register">S'inscrire</button>
                 <button type="reset" class="btn btn-danger col-lg-2  col-md-4 col-sm-6 m-2" id="reset">Annuler</button>
            </div>
 	</form>





