<div class="container-fluid">
	<div class = "page-header p-5">
		<h2 class="text-center text-secondary">Liste des inscrits </h2>
	</div>

	<table class="table table-hover" id="myTable">
  <thead>
    <tr>
      <th scope="col">Nom et prénom</th>
      <th scope="col">Email</th>
      <th scope="col">Tel</th>
      <th scope="col">Profil</th>
      <th scope="col">Université</th>
      <th scope="col">Activité</th>
      <th class="d-none d-lg-block" scope="col">Photo</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  	<?php foreach($users as $user): ?>
    <tr>
      <td><?= htmlspecialchars($user['nom']) ?> <em><?= htmlspecialchars($user['prenom']) ?></em></td>
      <td><?= htmlspecialchars($user['email']) ?></td>
      <td><?= htmlspecialchars($user['tel']) ?></td>
      <td><?= htmlspecialchars($user['profil']) ?></td>
      <td><?= htmlspecialchars($user['university']) ?></td>
      <td><?= htmlspecialchars($user['activity']) ?></td>
      <td class="d-none d-lg-block"><img src="uploads/<?=$user['photo']?>"  class="rounded-circle w-1" width="50px" height="50px" ></td>
      <td><a href="deleteUser.php?id=<?= intval($user['id']) ?>" title="Supprimer  l'utilisateur"><i class="fas fa-trash-alt"></i></a></td>
    </tr>
     <?php endforeach; ?>
  </tbody>
</table>

<script type="text/javascript">
	$(document).ready( function () {
    $('#myTable').DataTable();

} );
</script>
</div>